1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [3]:
import numpy as np

a = np.arange(10)

print(a)

[0 1 2 3 4 5 6 7 8 9]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.


In [9]:
a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [18]:
a = np.random.randint(1, 10, (5,5), dtype=int)
print(a)

[[ 4  2  5  6  7]
 [ 3  9  1  3  4]
 [ 6  2  8 10  4]
 [ 9  7  8  2  5]
 [ 7 10  5  8  3]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [22]:
a = np.random.random((4,4))
print(a)

[[0.36404665 0.38684217 0.2102673  0.50521407]
 [0.75434651 0.18651026 0.86040863 0.09443764]
 [0.28211722 0.30795697 0.68509199 0.1164458 ]
 [0.06077979 0.70079042 0.68100588 0.76835654]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [28]:
a = np.random.randint(1, 10, (5,), dtype = int)
b = np.random.randint(1, 10, (5,), dtype = int)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)


[5 1 3 2 6]
[7 8 9 6 4]
[12  9 12  8 10]
[-2 -7 -6 -4  2]
[35  8 27 12 24]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [69]:
a = np.random.randint(1, 10, (5,), dtype = int)
b = np.random.randint(1, 10, (5,), dtype = int)

print(a.dot(b))

147


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [68]:
a = np.random.randint(1, 10, (2,2), dtype = int)
b = np.random.randint(1, 10, (2,3), dtype = int)

print(a.dot(b))

[[30 12  9]
 [23  9  7]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [47]:
a = np.random.randint(1, 10, (3,3), dtype = int)
print(np.linalg.inv(a))


[[-0.29032258 -0.12903226  0.38709677]
 [ 0.24516129  0.26451613 -0.39354839]
 [ 0.03870968 -0.11612903  0.1483871 ]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [67]:
a = np.random.random((4,4))
print(a.T)

[[0.02668218 0.18723461 0.46569455 0.70217069]
 [0.29100528 0.97893994 0.15474352 0.12968963]
 [0.87348101 0.79724353 0.93396135 0.85024781]
 [0.77362124 0.77048916 0.48005918 0.17863675]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [66]:
a = np.random.randint(1, 10, (3,4), dtype=int)
b = np.random.randint(1, 10, (4), dtype=int)

print(a@b)

[ 51  99 107]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [65]:
a = np.random.randint(1, 10, (2,3), dtype=int)
b = np.random.randint(1, 10, (3), dtype=int)

print(a@b)

[ 42 106]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [64]:
a = np.random.randint(1, 10, (2,2), dtype=int)
b = np.random.randint(1, 10, (2,2), dtype=int)

print(a*b)

[[32 24]
 [25 12]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [73]:
a = np.random.randint(1, 10, (2,2), dtype=int)
b = np.random.randint(1, 10, (2,2), dtype=int)

print(a@b)

[[49 32]
 [26 20]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [77]:
a = np.random.randint(1, 100, (5,5), dtype=int)
print(np.sum(a))

1086


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [78]:
a = np.random.randint(1, 10, (4,4), dtype=int)
b = np.random.randint(1, 10, (4,4), dtype=int)
print(np.subtract(a,b))

[[-1  1 -7 -6]
 [ 4  2 -5 -1]
 [-3 -1 -4 -1]
 [ 3  2 -7 -6]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [101]:
a = np.random.random((3,3))
b = np.array([np.sum(a[:1]), np.sum(a[1:2]), np.sum(a[2:])])
c = np.sum(a, axis=1)
print(b)
print(c)

[1.75732995 1.08970638 2.27921007]
[1.75732995 1.08970638 2.27921007]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [95]:
a = np.random.randint(1, 10, (3,4), dtype=int)
print(np.square(a))
print(np.power(a, 2))

[[16 64 49 36]
 [36 49  9 49]
 [64  4 49 81]]
[[16 64 49 36]
 [36 49  9 49]
 [64  4 49 81]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [100]:
a = np.random.randint(1, 50, (4), dtype=int)
print(np.sqrt(a))
print(np.power(a, 1/2))

[6.92820323 6.32455532 4.79583152 4.35889894]
[6.92820323 6.32455532 4.79583152 4.35889894]
